-- MySQL
SELECT T.FLAVOR
FROM (SELECT F.FLAVOR, F.TOTAL_ORDER + SUM(J.TOTAL_ORDER)
      FROM FIRST_HALF F JOIN JULY J
      USING (FLAVOR)
      GROUP BY F.FLAVOR
      ORDER BY F.TOTAL_ORDER + SUM(J.TOTAL_ORDER) DESC) T
LIMIT 3;

-- Oracle
SELECT FLAVOR
FROM (SELECT F.FLAVOR, AVG(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER)
      FROM FIRST_HALF F, JULY J
      WHERE F.FLAVOR = J.FLAVOR
      GROUP BY F.FLAVOR
      ORDER BY AVG(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC)
WHERE ROWNUM <= 3;