WITH CTE AS (
  SELECT MEMBER_ID,
         RANK() OVER (ORDER BY COUNT(MEMBER_ID) DESC) AS RNK
    FROM REST_REVIEW
GROUP BY MEMBER_ID
)

  SELECT M.MEMBER_NAME, R.REVIEW_TEXT,
         DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
    FROM MEMBER_PROFILE M, REST_REVIEW R, CTE C
   WHERE C.RNK = 1
         AND M.MEMBER_ID = R.MEMBER_ID
         AND R.MEMBER_ID = C.MEMBER_ID
         AND M.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE, R.REVIEW_TEXT;