-- 오답
SELECT  B.CAR_ID,
        A.CAR_TYPE,
        (A.DAILY_FEE * 30 * ((100-D.DISCOUNT_RATE)/100)) AS FEE
FROM    CAR_RENTAL_COMPANY_CAR              A,
        CAR_RENTAL_COMPANY_RENTAL_HISTORY   B,
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN    C,
        (SELECT SC.CAR_TYPE, SC.DISCOUNT_RATE
         FROM   CAR_RENTAL_COMPANY_DISCOUNT_PLAN SC
         WHERE  DURATION_TYPE = '30일 이상') D
WHERE   A.CAR_ID = B.CAR_ID
AND     A.CAR_TYPE = C.CAR_TYPE
AND     A.CAR_TYPE = D.CAR_TYPE
AND     C.CAR_TYPE = D.CAR_TYPE
AND     C.DISCOUNT_RATE = D.DISCOUNT_RATE
AND     A.CAR_TYPE IN ('세단', 'SUV')
AND     NOT EXISTS (
            SELECT  1
            FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY HC
            WHERE   HC.CAR_ID = A.CAR_ID
              AND   HC.START_DATE <= DATE '2022-11-01'
              AND   HC.END_DATE   >= DATE '2022-11-30'
        )
AND     (A.DAILY_FEE * 30 * (1-(D.DISCOUNT_RATE/100))) >= 500000
AND     (A.DAILY_FEE * 30 * (1-(D.DISCOUNT_RATE/100))) < 2000000
ORDER BY
        FEE DESC,
        A.CAR_TYPE,
        B.CAR_ID DESC
;
