-- 오답
SELECT  DISTINCT B.CAR_ID,
        A.CAR_TYPE,
        (A.DAILY_FEE * 30 * D.DISCOUNT_RATE) AS FEE
FROM    CAR_RENTAL_COMPANY_CAR              A,
        CAR_RENTAL_COMPANY_RENTAL_HISTORY   B,
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN    C,
        (SELECT SC.CAR_TYPE, SC.DISCOUNT_RATE
         FROM   CAR_RENTAL_COMPANY_DISCOUNT_PLAN SC
         WHERE  1=1
         AND    SC.CAR_TYPE IN ('세단', 'SUV')
         AND    DURATION_TYPE = '30일 이상') D
WHERE   1=1
AND     A.CAR_ID = B.CAR_ID
AND     A.CAR_TYPE = C.CAR_TYPE
AND     A.CAR_TYPE = D.CAR_TYPE
AND     C.CAR_TYPE = D.CAR_TYPE
AND     A.CAR_TYPE IN ('세단', 'SUV')
AND     TO_CHAR(B.START_DATE, 'YYYYMMDD') <= '20221101'
AND     TO_CHAR(B.END_DATE, 'YYYYMMDD') >= '20221130'
ORDER BY
        FEE DESC, A.CAR_TYPE, B.CAR_ID DESC
;
