SELECT  DISTINCT A.CAR_ID,
        A.CAR_TYPE,
        (A.DAILY_FEE * 30 * ((100-C.DISCOUNT_RATE)/100)) AS FEE
FROM    CAR_RENTAL_COMPANY_CAR              A,
        CAR_RENTAL_COMPANY_RENTAL_HISTORY   B,
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN    C
WHERE   A.CAR_ID = B.CAR_ID
AND     A.CAR_TYPE = C.CAR_TYPE
AND     C.DURATION_TYPE = '30일 이상'
AND     A.CAR_TYPE IN ('세단', 'SUV')
AND     A.CAR_ID NOT IN
        (SELECT DISTINCT(CAR_ID)
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
         WHERE START_DATE <= DATE '2022-11-30'
         AND END_DATE >= DATE '2022-11-01'
        )
AND     (A.DAILY_FEE * 30 * (1-(C.DISCOUNT_RATE/100))) >= 500000
AND     (A.DAILY_FEE * 30 * (1-(C.DISCOUNT_RATE/100))) < 2000000
ORDER BY
        FEE DESC,
        A.CAR_TYPE,
        A.CAR_ID DESC
;
