SELECT  INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM    ANIMAL_INS INS,
        ANIMAL_OUTS OUTS
WHERE   INS.ANIMAL_ID = OUTS.ANIMAL_ID
AND     INS.ANIMAL_TYPE = OUTS.ANIMAL_TYPE
AND     INS.NAME = OUTS.NAME
AND     INS.SEX_UPON_INTAKE LIKE 'Intact%' -- 보호소에 들어올 때 중성화 X
AND     (OUTS.SEX_UPON_OUTCOME LIKE 'Spayed%' OR OUTS.SEX_UPON_OUTCOME LIKE 'Neutered%') -- 보호소에서 나갈 때 중성화
;
