WITH CTE AS (
    SELECT DISTINCT
           YEAR(B.SALES_DATE) AS YEAR,
           MONTH(B.SALES_DATE) AS MONTH,
           A.USER_ID AS PURCHASED_USERS
      FROM USER_INFO A, ONLINE_SALE B
     WHERE DATE_FORMAT(A.JOINED, '%Y-%m-%d') LIKE '2021%' AND A.USER_ID = B.USER_ID
)

  SELECT YEAR, MONTH, COUNT(PURCHASED_USERS) AS PURCHASED_USERS,
         ROUND(COUNT(PURCHASED_USERS) / (SELECT COUNT(USER_ID) FROM USER_INFO
                                          WHERE DATE_FORMAT(JOINED, '%Y-%m-%d') LIKE '2021%'), 1)
         AS PURCHASED_RATIO
    FROM CTE
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;