WITH CNT AS (
  SELECT WRITER_ID, COUNT(WRITER_ID) AS COUNT
    FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
)

  SELECT A.USER_ID, A.NICKNAME,
         CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS 전체주소,
         CONCAT(SUBSTR(A.TLNO, 1, 3), '-', SUBSTR(A.TLNO, 4, 4), '-', SUBSTR(A.TLNO, 8, 4)) AS 전화번호
    FROM USED_GOODS_USER A, CNT B
   WHERE A.USER_ID = B.WRITER_ID AND B.COUNT >= 3
ORDER BY A.USER_ID DESC;