WITH PARAM1 AS (
    SELECT (100-DISCOUNT_RATE)/100
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상'
)
, PARAM2 AS (
    SELECT (100-DISCOUNT_RATE)/100
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'
)
, PARAM3 AS (
    SELECT (100-DISCOUNT_RATE)/100
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상'
)

  SELECT   HISTORY_ID
         , CASE WHEN DATEDIFF(END_DATE, START_DATE) >= 90
                THEN FLOOR(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) * (SELECT * FROM PARAM3))
                WHEN DATEDIFF(END_DATE, START_DATE) >= 30
                THEN FLOOR(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) * (SELECT * FROM PARAM2))
                WHEN DATEDIFF(END_DATE, START_DATE) >= 7
                THEN FLOOR(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) * (SELECT * FROM PARAM1))
                ELSE DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) END AS FEE
    FROM   CAR_RENTAL_COMPANY_CAR A
         , CAR_RENTAL_COMPANY_RENTAL_HISTORY B
   WHERE A.CAR_ID = B.CAR_ID AND A.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;