-- WITH CTE AS (
--     SELECT B.ITEM_ID AS CAN_DEVELOP,
--            B.PARENT_ITEM_ID AS START_ID,
--            A.ITEM_NAME AS START_NAME
--       FROM ITEM_INFO A, ITEM_TREE B
--      WHERE B.PARENT_ITEM_ID = A.ITEM_ID
-- )

--   SELECT DISTINCT A.ITEM_ID, A.ITEM_NAME, A.RARITY
--     FROM ITEM_INFO A, CTE B
--    WHERE A.ITEM_ID NOT IN (SELECT START_ID FROM CTE)
-- ORDER BY A.ITEM_ID DESC;

  SELECT ITEM_ID, ITEM_NAME, RARITY
    FROM ITEM_INFO
   WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID
                           FROM ITEM_TREE
                          WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC;