-- MySQL
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS,
       DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE YEAR(A.CREATED_DATE) = 2022
  AND MONTH(A.CREATED_DATE) = 10
  AND A.BOARD_ID = B.BOARD_ID
ORDER BY B.CREATED_DATE, A.TITLE;

-- Oracle
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS,
       TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') as CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE SUBSTR(TO_CHAR(A.CREATED_DATE, 'YYYY-MM-DD'), 1, 4) = 2022
  AND SUBSTR(TO_CHAR(A.CREATED_DATE, 'YYYY-MM-DD'), 6, 2) = 10
  AND A.BOARD_ID = B.BOARD_ID
ORDER BY B.CREATED_DATE, A.TITLE;