-- MySQL
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;

-- Oracle
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
WHERE SUBSTR(TO_CHAR(PUBLISHED_DATE, 'YYYYMMDD'), 0 , 4) = 2021 AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;