-- MySQL
SELECT COUNT(USER_ID) AS USERS
FROM USER_INFO
WHERE YEAR(JOINED) = 2021 AND AGE BETWEEN 20 AND 29;

-- Oracle
SELECT COUNT(USER_ID) AS USERS
FROM USER_INFO
WHERE SUBSTR(TO_CHAR(JOINED, 'YYYY-MM-DD'), 1, 4) = '2021'
  AND AGE BETWEEN 20 AND 29;