  SELECT A.ITEM_ID, B.ITEM_NAME, B.RARITY
    FROM (SELECT B.ITEM_ID AS ITEM_ID
            FROM ITEM_INFO A
       LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
           WHERE A.RARITY = "RARE"
             AND B.ITEM_ID IS NOT NULL) A, ITEM_INFO B
   WHERE A.ITEM_ID = B.ITEM_ID
ORDER BY A.ITEM_ID DESC;