-- MySQL
SELECT MEMBER_ID, MEMBER_NAME, GENDER, 
       DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND MONTH(DATE_OF_BIRTH) = 3 AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;

-- Oracle
SELECT MEMBER_ID, MEMBER_NAME, GENDER, 
       TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W'
  AND SUBSTR(TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD'), 6, 2) = 3
  AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;