SELECT DISTINCT O1.USER_ID AS USER_ID, O1.PRODUCT_ID AS PRODUCT_ID
FROM ONLINE_SALE O1, ONLINE_SALE O2
WHERE O1.USER_ID = O2.USER_ID
  AND O1.PRODUCT_ID = O2.PRODUCT_ID
  AND O1.ONLINE_SALE_ID != O2.ONLINE_SALE_ID
ORDER BY O1.USER_ID, O1.PRODUCT_ID DESC;