SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO FO,
    (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'BASS') FB,
    (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'SNAPPER') FS
WHERE (FO.FISH_TYPE = FB.FISH_TYPE) OR (FO.FISH_TYPE = FS.FISH_TYPE);