SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D,
    (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') SP,
    (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') SC
WHERE (D.SKILL_CODE & SP.CODE = SP.CODE) OR (D.SKILL_CODE & SC.CODE = SC.CODE)
ORDER BY ID;