-- [GEN1] 1세대 대장균 추출, [GEN2] 2세대 대장균 추출
WITH GEN1 AS (
    SELECT ID
      FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
),
     GEN2 AS (
    SELECT A.ID AS ID, A.PARENT_ID AS PARENT_ID
      FROM ECOLI_DATA A
      JOIN GEN1 ON A.PARENT_ID = GEN1.ID
)

SELECT B.ID
  FROM ECOLI_DATA B
  JOIN GEN2 ON B.PARENT_ID = GEN2.ID;