-- MySQL
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS,
       ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO A, REST_REVIEW B
WHERE (LEFT(A.ADDRESS, 3) = '서울시' OR LEFT(A.ADDRESS, 5) = '서울특별시')
  AND A.REST_ID = B.REST_ID
GROUP BY REST_ID
ORDER BY ROUND(AVG(B.REVIEW_SCORE), 2) DESC, A.FAVORITES DESC;

-- Oracle
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS,
       ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO A, REST_REVIEW B
WHERE (SUBSTR(A.ADDRESS, 0, 3) = '서울시' OR SUBSTR(A.ADDRESS, 0, 5) = '서울특별시')
      AND A.REST_ID = B.REST_ID
GROUP BY A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS
ORDER BY ROUND(AVG(B.REVIEW_SCORE), 2) DESC, A.FAVORITES DESC;