-- MySQL
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
      FROM ONLINE_SALE
      WHERE DATE_FORMAT(SALES_DATE, '%Y') = 2022 AND DATE_FORMAT(SALES_DATE, '%m') = 03 
      UNION ALL
      SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
      FROM OFFLINE_SALE
      WHERE DATE_FORMAT(SALES_DATE, '%Y') = 2022 AND DATE_FORMAT(SALES_DATE, '%m') = 03) A
ORDER BY DATE_FORMAT(SALES_DATE, '%Y-%m-%d'), PRODUCT_ID, USER_ID;

-- Oracle
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
      FROM ONLINE_SALE
      WHERE SUBSTR(TO_CHAR(SALES_DATE, 'YYYYMMDD'), 1, 4) = '2022'
        AND SUBSTR(TO_CHAR(SALES_DATE, 'YYYYMMDD'), 5, 2) = '03'
      UNION ALL
      SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
      FROM OFFLINE_SALE
      WHERE SUBSTR(TO_CHAR(SALES_DATE, 'YYYYMMDD'), 1, 4) = '2022'
        AND SUBSTR(TO_CHAR(SALES_DATE, 'YYYYMMDD'), 5, 2) = '03') A
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;