-- # 1
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
       T.YEAR_MAX - E.SIZE_OF_COLONY AS YEAR_DEV,
       E.ID AS ID
FROM ECOLI_DATA E, (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
                           MAX(SIZE_OF_COLONY) AS YEAR_MAX
                           FROM ECOLI_DATA
                           GROUP BY YEAR(DIFFERENTIATION_DATE)) T
WHERE YEAR(E.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY YEAR, T.YEAR_MAX - E.SIZE_OF_COLONY;

-- # 2
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
       MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,
       ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV;