-- Wrong Answer
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, MAX(PRICE) AS PRICE FROM FOOD_PRODUCT;

-- Correct Answer
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT, (SELECT MAX(PRICE) AS P FROM FOOD_PRODUCT) T
WHERE PRICE = T.P;