WITH MY_HR_GRADE AS (
      SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE
    GROUP BY EMP_NO
)

  SELECT C.SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
    FROM HR_DEPARTMENT A, HR_EMPLOYEES B, MY_HR_GRADE C
   WHERE B.EMP_NO = C.EMP_NO
GROUP BY C.EMP_NO
ORDER BY C.SCORE DESC
   LIMIT 1;