WITH MY_PRODUCT AS (
    SELECT PRICE DIV 10000 AS PRICE, COUNT(*) AS PRODUCTS
      FROM PRODUCT
  GROUP BY PRICE DIV 10000
  ORDER BY PRICE DIV 10000
)

SELECT PRICE*10000, PRODUCTS
  FROM MY_PRODUCT;