WITH CTE AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
      FROM REST_INFO
  GROUP BY FOOD_TYPE
  ORDER BY FOOD_TYPE DESC
)

  SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, B.FAVORITES AS FAVORITES
    FROM REST_INFO A, CTE B
   WHERE A.FOOD_TYPE = B.FOOD_TYPE
     AND A.FAVORITES = B.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;