SELECT E.USER_ID, E.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B, USED_GOODS_USER E
WHERE B.WRITER_ID = E.USER_ID
  AND B.STATUS = 'DONE'
GROUP BY E.USER_ID, E.NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;