WITH CTE AS (
  SELECT ID, FISH_TYPE, IFNULL(LENGTH, 10) AS MYLENGTH
    FROM FISH_INFO
)

  SELECT COUNT(*) AS FISH_COUNT, MAX(MYLENGTH) AS MAX_LENGTH, FISH_TYPE
    FROM CTE
GROUP BY FISH_TYPE
  HAVING AVG(MYLENGTH) >= 33
ORDER BY FISH_TYPE;