  SELECT A.DEPT_ID AS DEPT_ID,
         B.DEPT_NAME_EN AS DEPT_NAME_EN,
         ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES A, HR_DEPARTMENT B
   WHERE A.DEPT_ID = B.DEPT_ID
GROUP BY A.DEPT_ID
ORDER BY AVG(SAL) DESC;