-- 사번별 SCORE 평균, BONUS 비율 테이블
WITH CTE AS (
  SELECT EMP_NO, AVG(SCORE) AS FIN_SCORE,
         CASE WHEN AVG(SCORE) >= 96 THEN 'S'
              WHEN AVG(SCORE) >= 90 THEN 'A'
              WHEN AVG(SCORE) >= 80 THEN 'B'
              ELSE 'C' END AS GRADE,
         CASE WHEN AVG(SCORE) >= 96 THEN 0.2
              WHEN AVG(SCORE) >= 90 THEN 0.15
              WHEN AVG(SCORE) >= 80 THEN 0.10
              ELSE 0 END AS BONUS
    FROM HR_GRADE
GROUP BY EMP_NO
)

  SELECT A.EMP_NO, A.EMP_NAME, B.GRADE AS GRADE, (A.SAL * B.BONUS) AS BONUS
    FROM HR_EMPLOYEES A, CTE B
   WHERE A.EMP_NO = B.EMP_NO
ORDER BY EMP_NO;