WITH CTE AS (
      SELECT CATEGORY, MAX(PRICE) AS PRICE
        FROM FOOD_PRODUCT
       WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
)

  SELECT A.CATEGORY, B.PRICE AS MAX_PRICE, A.PRODUCT_NAME
    FROM FOOD_PRODUCT A, CTE B
   WHERE A.CATEGORY = B.CATEGORY
     AND A.PRICE = B.PRICE
ORDER BY MAX_PRICE DESC;