WITH CTE AS (
  SELECT HOST_ID, COUNT(HOST_ID) AS CNT
    FROM PLACES
GROUP BY HOST_ID
)

  SELECT A.ID, A.NAME, A.HOST_ID
    FROM PLACES A, CTE B
   WHERE A.HOST_ID = B.HOST_ID AND B.CNT >= 2
ORDER BY ID;